#2. problemas de la plataforma Rosalind
#Encontrar porcentaje de GC


Ros6404<-("CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCCTCCCACTAATAATTCTGAGG")
Ros6404

Ros5959<-("CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCTATATCCATTTGTCAGCAGACACGC")
Ros5959


Ros0808<-("CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGACTGGGAACCTGCGGGCAGTAGGTGGAAT")
Ros0808

Ros0808$prob <- prop.table(Ros0808)
Ros0808<-round(prop.table(Ros0808$freq), 4)*100

Ros0808 %>%
library(dplyr)
Ros0808 %>% mutate(prob = prop.table(freq))
# O también
Ros0808%>% mutate(prob = freq / sum(freq))

Ros0808<-dplyr